##
## SPDX-FileCopyrightText: 2025 Splunk LLC
## SPDX-License-Identifier: LicenseRef-Splunk-8-2021
##
##
[script:setup]
python.version = python3
python.required = 3.9, 3.13
match=/SetupService
handler=setupservice.SetupService
