[adx_breakglass_accounts]
filename = adx_breakglass_accounts.csv
case_sensitive_match = false

[adx_event_catalog]
filename = adx_event_catalog.csv

[adx_logon_types]
filename = adx_logon_types.csv

[adx_failure_codes]
filename = adx_failure_codes.csv
case_sensitive_match = false

[adx_replication_events]
filename = adx_replication_events.csv
