[audit_queue_fill]
definition = index=_internal source=*metrics.log* group=queue | eval pct_full=round((current_size_kb/max_size_kb)*100,1)
iseval = 0

[audit_hostwide_metrics]
definition = index=_internal source=*metrics.log* group=hostwide
iseval = 0

[audit_per_index_thruput]
definition = index=_internal source=*metrics.log* group=per_index_thruput
iseval = 0

[audit_errors_warnings]
definition = index=_internal sourcetype=splunkd (log_level=ERROR OR log_level=WARN)
iseval = 0

[audit_scheduler_log]
definition = index=_internal source=*scheduler.log*
iseval = 0

[audit_login_events]
definition = index=_audit action=login
iseval = 0

[audit_forwarder_connections]
definition = index=_internal source=*metrics.log* group=tcpin_connections
iseval = 0

[audit_rest_indexes]
definition = | rest /services/data/indexes splunk_server=local
iseval = 0

[audit_rest_users]
definition = | rest /services/authentication/users splunk_server=local
iseval = 0

[audit_rest_server_settings]
definition = | rest /services/server/settings splunk_server=local
iseval = 0

[audit_rest_sslconfig]
definition = | rest /services/configs/conf-server splunk_server=local | search title=sslConfig
iseval = 0

[audit_rest_kvstore_status]
definition = | rest /services/kvstore/status splunk_server=local
iseval = 0

[audit_rest_license_pools]
definition = | rest /services/licenser/pools splunk_server=local
iseval = 0

[audit_rest_saved_searches_acl]
definition = | rest /services/saved/searches splunk_server=local
iseval = 0

[audit_rest_partitions_space]
definition = | rest /services/server/status/partitions-space splunk_server=local
iseval = 0
